### PR TITLE
NDK updated to r14

### PR DESCRIPTION
**Pull request by koral--**

### CODE REVIEW

**Comment by viktorbenei** [comment]
The error is:

```
ApplyLayer exit status 1 stdout:  stderr: write /opt/android-ndk-tmp/android-ndk-r14/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/3.8/lib/linux/libclang_rt.asan-i686.a: no space left on device
```

Did the size of NDK grow significantly since 13?

In any case, thank you for the PR and we'll try to check why there's not enough space for the new NDK ASAP

**Comment by koral--** [comment]
Yes, it grown:
```
root@30f4cd06dfc0:/bitrise/src# du -hcs android-ndk-r13b
2.4G	android-ndk-r13b
2.4G	total
root@30f4cd06dfc0:/bitrise/src# du -hcs /opt/android-ndk/
2.8G	/opt/android-ndk/
2.8G	total
```

**Comment by viktorbenei** [comment]
Thanks @koral-- !

We'll try to review this and push it through ASAP, but it most likely won't be a part of this weekend's update, only next week's - the update images are created in less than 24 hours, so that we can run tests with them on Friday (and fix anything if required) before the deploy on Saturday.

**Comment by viktorbenei** [comment]
We increased storage/disk space on the Linux/Android stack, re-run of the PR was successful with the increased storage.

Schedule: We'll merge this PR next week, and will be part of next weekend's updates!

**Comment by viktorbenei** [comment]
Perfect, re-build success and all tests passed - will be part of this weekend's updates. Thanks again for the PR @koral-- ! ;)

**Comment by jfirebaugh** [comment]
Could you please add this change to the CHANGELOG?

**Comment by koral--** [comment]
I'm not sure who should update a CHANGELOG and whether version number is correct (I've used date of merge). If PR authors should do it, there should be such information in REDAME perhaps.

BTW it seems that tag for this change is also missing and there is no release for current latest tag: https://github.com/bitrise-docker/android-ndk/releases

**Comment by viktorbenei** [comment]
Ohh, you're right @koral-- we forgot to tag it here; I'll do that ASAP!

it's less important to mark releases here for our docker images as the tags on docker hub are completely separate ones, mainly because we do scheduled builds (alphas are rebuilt every day, pinned ones once a week when every test passes on the specified alpha).

But in any case I'll do the README and tag update ASAP, thanks for the reminder!

**Comment by viktorbenei** [comment]
Done, CHANGELOG merged from #49 and tag added to the repo too - thanks again @koral-- for all the contribution, and thanks @jfirebaugh for the reminder!

**Pull request merged**
